hunter_config(CURL VERSION ${HUNTER_CURL_VERSION} CMAKE_ARGS HTTP_ONLY=ON CMAKE_USE_OPENSSL=OFF CMAKE_USE_LIBSSH2=OFF CURL_CA_PATH=none)
hunter_config(Boost VERSION ${HUNTER_Boost_VERSION} CMAKE_ARGS Boost_Boost=ON Boost_FILESYSTEM=ON Boost_THREAD=ON Boost_MULTITHREADED=ON)
