hunter_config(Boost
	VERSION 1.81.0
	COMPONENTS headers
	CMAKE_ARGS CMAKE_BUILD_TYPE=Release MSVC_VERSION=1939 
)
hunter_config(CURL
	VERSION ${HUNTER_CURL_VERSION}
	CMAKE_ARGS HTTP_ONLY=ON CMAKE_USE_OPENSSL=OFF CMAKE_USE_LIBSSH2=OFF CURL_CA_PATH=none
)
hunter_config(CLI11 
	VERSION 1.9.1
)
hunter_config(OpenSSL
	URL https://github.com/openssl/openssl/releases/download/openssl-3.3.0-alpha1/openssl-3.3.0-alpha1.tar.gz
	SHA1 a0afa369e07f66c67db7f815e129e9fd1fb62072
	CMAKE_ARGS ARCH=VC-WIN64A-masm OPENSSL_USE_STATIC_LIBS=ON OPENSSL_MSVC_STATIC_RT=ON ASM_SUPPORT=ON MSVC_VERSION=1939
)
